### ISSUE TITLE
dependencies: fialing due to redis pin

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-cli#101]
``` python
Traceback (most recent call last):
  File "/home/ppanero/.virtualenvs/zach/lib/python3.6/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/home/ppanero/.virtualenvs/zach/lib/python3.6/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/ppanero/.virtualenvs/zach/lib/python3.6/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (redis 3.4.0 (/home/ppanero/.virtualenvs/zach/lib/python3.6/site-packages), Requirement.parse('redis<3.4.0,>=3.3.11'), {'invenio-cli'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ppanero/.virtualenvs/zach/bin/invenio-cli", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/ppanero/.virtualenvs/zach/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    @_call_aside
  File "/home/ppanero/.virtualenvs/zach/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3236, in _call_aside
    f(*args, **kwargs)
  File "/home/ppanero/.virtualenvs/zach/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3265, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/ppanero/.virtualenvs/zach/lib/python3.6/site-packages/pkg_resources/__init__.py", line 586, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/ppanero/.virtualenvs/zach/lib/python3.6/site-packages/pkg_resources/__init__.py", line 599, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/ppanero/.virtualenvs/zach/lib/python3.6/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'redis<3.4.0,>=3.3.11' distribution was not found and is required by invenio-cli

```

Redis gets installed with `<3.4.0` in `invenio-cli`. Then upon `invenio-cli build` the installation happens according to the Pipfile where the pin of redis is only `>=2.10` or similar (coming form several invenio packages not invenio-app-rdm per se.

This issue has already happened with other libraries. But I think is going to be fixed when `invenio-cli` and the `invenio` commands/envs are separated? 

@fenekku could you confirm this (my assumption of it getting fixed). For now im just pinning in local, can provide a PR if its not the case of it getting fixed.

@zzacharo be aware of this when testing ;)

**Comment by fenekku** [comment]
Yes, I am planning on removing the redis dependency from invenio-cli, so it shouldn't be a problem anymore.
