### ISSUE TITLE
demo: not working on containerize

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-cli#115]
``` console
$ invenio-cli demo --containers
Traceback (most recent call last):
  File "/home/ppanero/.virtualenvs/s3/bin/invenio-cli", line 11, in <module>
    load_entry_point('invenio-cli', 'console_scripts', 'invenio-cli')()
  File "/home/ppanero/.virtualenvs/s3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ppanero/.virtualenvs/s3/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ppanero/.virtualenvs/s3/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ppanero/.virtualenvs/s3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ppanero/.virtualenvs/s3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ppanero/Workspace/inveniosw/invenio-cli/invenio_cli/cli.py", line 116, in demo
    commands.demo()
  File "/home/ppanero/Workspace/inveniosw/invenio-cli/invenio_cli/helpers/commands.py", line 44, in __getattr__
    return getattr(self.environment, name)
AttributeError: 'ContainerizedCommands' object has no attribute 'demo'

```

Basically the demo command uses the `Commands` factory, however the `ContainerizedCommands` object does not have the demo function.

Side note: I thought we were removing the `Commands` object factory?

**Comment by fenekku** [comment]
Yes we are, but we weren't planning on doing it in this sprint. See https://github.com/inveniosoftware/invenio-cli/issues/108 : which was a poor description of this situation :)
