### ISSUE TITLE
group check 

### ISSUE THREAD

**Issue by cfgamboa** [inveniosoftware/invenio-cli#204]
Package version (if known): invenio-cli, version 0.19.4

## Describe the bug
The user is part of the docker group as instructed  here https://inveniordm.docs.cern.ch/install/

## 1.
```
su - invenio
Last login: Fri Dec 18 11:47:59 EST 2020 on pts/3 
```
## 2.
```
id invenio
uid=1002(invenio) gid=1000(invenio) groups=1001(docker),1000(invenio)
```
## 3.

```
invenio-cli check-requirements
Checking pre-requirements...
Checking Python version...
Traceback (most recent call last):
  File "/opt/invenio/.local/bin/invenio-cli", line 8, in <module>
    sys.exit(invenio_cli())
  File "/opt/invenio/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/invenio/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/invenio/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/invenio/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/invenio/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/invenio/.local/lib/python3.6/site-packages/invenio_cli/cli/cli.py", line 53, in check_requirements
    run_steps(steps, on_fail, on_success)
  File "/opt/invenio/.local/lib/python3.6/site-packages/invenio_cli/cli/utils.py", line 22, in run_steps
    result = test.execute()
  File "/opt/invenio/.local/lib/python3.6/site-packages/invenio_cli/commands/steps.py", line 27, in execute
    return self.func(**self.args)
  File "/opt/invenio/.local/lib/python3.6/site-packages/invenio_cli/commands/requirements.py", line 78, in check_python_version
    version = cls._version_from_string(result.output.strip())
  File "/opt/invenio/.local/lib/python3.6/site-packages/invenio_cli/commands/requirements.py", line 24, in _version_from_string
    return groups.group(0)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by ppanero** [comment]
Related to https://github.com/inveniosoftware/invenio-cli/issues/205
