### ISSUE TITLE
check-requirements fail on vanilla debian 10 due to python version

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-cli#214]
Package version (if known): 0.20.

## Describe the bug

``invenio-cli check-requirements`` fails on a vanilla Debian 10 when trying to determine the Python version.

## Steps to Reproduce

```
vagrant init debian/buster64
vagrant up
vagrant ssh
```

```
sudo apt update
sudo apt -y upgrade
sudo apt install -y python3-dev python3-pip
sudo apt install 
export PATH=/home/vagrant/.local/bin:$PATH
pip3 install invenio-cli
invenio-cli check-requirements
```
## Additional context

```
Checking Python version...
Traceback (most recent call last):
  File "/home/vagrant/.local/bin/invenio-cli", line 10, in <module>
    sys.exit(invenio_cli())
  File "/home/vagrant/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/vagrant/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/vagrant/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vagrant/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vagrant/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/vagrant/.local/lib/python3.7/site-packages/invenio_cli/cli/cli.py", line 53, in check_requirements
    run_steps(steps, on_fail, on_success)
  File "/home/vagrant/.local/lib/python3.7/site-packages/invenio_cli/cli/utils.py", line 22, in run_steps
    result = test.execute()
  File "/home/vagrant/.local/lib/python3.7/site-packages/invenio_cli/commands/steps.py", line 27, in execute
    return self.func(**self.args)
  File "/home/vagrant/.local/lib/python3.7/site-packages/invenio_cli/commands/requirements.py", line 78, in check_python_version
    version = cls._version_from_string(result.output.strip())
  File "/home/vagrant/.local/lib/python3.7/site-packages/invenio_cli/commands/requirements.py", line 24, in _version_from_string
    return groups.group(0)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by max-moser** [comment]
It looks like Debian 10 has `python` symlinked to `python2`, which apparently prints the version info (`python --version`) to stderr instead of stdout
