### ISSUE TITLE
Containerized rdm setup fails due to setuptools 58 use_2to3

### ISSUE THREAD

**Issue by zyzzyxdonta** [inveniosoftware/invenio-cli#270]
Package version (if known): 6.0.0

## Describe the bug
When following [the install instructions for rdm](https://inveniordm.docs.cern.ch/install/), the following step fails:

```bash
invenio-cli containers start --lock --build --setup
```

## Steps to Reproduce
1. Follow the install instructions
2. On step 4 see error

```
Starting InvenioRDM instance...
Locking python dependencies...
Locking [dev-packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success! 
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed! 
ERROR:pip.subprocessor:Command errored out with exit status 1:
 command: /root/rodare/.venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-resolver-2lwkxo8g/fs/setup.py'"'"'; __file__='"'"'/tmp/pip-resolver-2lwkxo8g/fs/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-resolver-2lwkxo8g/fs/pip-egg-info
     cwd: /tmp/pip-resolver-2lwkxo8g/fs/
Complete output (1 lines):
error in fs setup command: use_2to3 is invalid.
----------------------------------------
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 764, in <module>
    main()
  File "/root/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 758, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system, parsed.write,
  File "/root/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 741, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
  File "/root/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 702, in resolve_packages
    results, resolver = resolve(
  File "/root/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 684, in resolve
    return resolve_deps(
  File "/root/.local/lib/python3.8/site-packages/pipenv/utils.py", line 1397, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/root/.local/lib/python3.8/site-packages/pipenv/utils.py", line 1110, in actually_resolve_deps
    resolver.resolve()
  File "/root/.local/lib/python3.8/site-packages/pipenv/utils.py", line 825, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/root/.local/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 180, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/root/.local/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 268, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/root/.local/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 383, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/root/.local/lib/python3.8/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 229, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/root/.local/lib/python3.8/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 350, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(
  File "/root/.local/lib/python3.8/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 306, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/root/.local/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/legacy_resolve.py", line 339, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/root/.local/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/legacy_resolve.py", line 287, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/root/.local/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
    abstract_dist = _get_prepared_distribution(
  File "/root/.local/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/root/.local/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/root/.local/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 564, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/root/.local/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 538, in _generate_metadata
    return generate_metadata_legacy(
  File "/root/.local/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/operations/build/metadata_legacy.py", line 115, in generate_metadata
    call_subprocess(
  File "/root/.local/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pipenv.patched.notpip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Failed to start containerized instance.
```

## Expected behavior

No error

## Additional context

-

**Comment by roelj** [comment]
Just a bystander here; I ran into the exact same issue, and figured out that I selected a Python version that didn't match with the one in my virtual environment. After selecting the matching version(`3.9` in my case), I could perform a local installation just file.

Perhaps the Python version can be automatically detected, and then put as the default option?

**Comment by zyzzyxdonta** [comment]
What exactly do you mean by Python version in the virtual environment? The venv is set up by invenio-cli. On my system, I have Python 3.8.10 installed, so I chose 3.8 in the setup.

**Comment by ppanero** [comment]
This seems to be the `setuptools` version. As per research of @lnielsen:

> I found the culprit https://setuptools.readthedocs.io/en/latest/history.html
setuptools v57 vs v58
#2769: Build now fails fast when use_2to3 is supplied.
#2086: Removed support for 2to3 during builds. Projects should port to a unified codebase or pin to an older version of Setuptools using PEP 518 build-requires.

Installing the latest minor of v57 should work
