### ISSUE TITLE
invenio-cli services setup fails

### ISSUE THREAD

**Issue by apirogov** [inveniosoftware/invenio-cli#273]
## Describe the bug
When trying the local install as explained [here](https://inveniordm.docs.cern.ch/install/build-setup-run/), I get the following error after `invenio-cli services setup`:

```
Creating indices...
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/invenio-rdm-test-1Upwmhg8/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/user/.local/share/virtualenvs/invenio-rdm-test-1Upwmhg8/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/user/.local/share/virtualenvs/invenio-rdm-test-1Upwmhg8/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1371, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/invenio-rdm-test-1Upwmhg8/lib/python3.9/site-packages/elasticsearch/connection/http_urllib3.py", line 251, in perform_request
    response = self.pool.urlopen(
  File "/home/user/.local/share/virtualenvs/invenio-rdm-test-1Upwmhg8/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/user/.local/share/virtualenvs/invenio-rdm-test-1Upwmhg8/lib/python3.9/site-packages/urllib3/util/retry.py", line 507, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/user/.local/share/virtualenvs/invenio-rdm-test-1Upwmhg8/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/user/.local/share/virtualenvs/invenio-rdm-test-1Upwmhg8/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/user/.local/share/virtualenvs/invenio-rdm-test-1Upwmhg8/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/user/.local/share/virtualenvs/invenio-rdm-test-1Upwmhg8/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1371, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/invenio-rdm-test-1Upwmhg8/bin/invenio", line 8, in <module>
    sys.exit(cli())
  File "/home/user/.local/share/virtualenvs/invenio-rdm-test-1Upwmhg8/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/invenio-rdm-test-1Upwmhg8/lib/python3.9/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/invenio-rdm-test-1Upwmhg8/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/share/virtualenvs/invenio-rdm-test-1Upwmhg8/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/share/virtualenvs/invenio-rdm-test-1Upwmhg8/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/share/virtualenvs/invenio-rdm-test-1Upwmhg8/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/share/virtualenvs/invenio-rdm-test-1Upwmhg8/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/invenio-rdm-test-1Upwmhg8/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/.local/share/virtualenvs/invenio-rdm-test-1Upwmhg8/lib/python3.9/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/user/.local/share/virtualenvs/invenio-rdm-test-1Upwmhg8/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/invenio-rdm-test-1Upwmhg8/lib/python3.9/site-packages/invenio_search/cli.py", line 34, in inner
    cluster_ver = current_search.cluster_version[0]
  File "/home/user/.local/share/virtualenvs/invenio-rdm-test-1Upwmhg8/lib/python3.9/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/user/.local/share/virtualenvs/invenio-rdm-test-1Upwmhg8/lib/python3.9/site-packages/invenio_search/ext.py", line 229, in cluster_version
    versionstr = self.client.info()['version']['number']
  File "/home/user/.local/share/virtualenvs/invenio-rdm-test-1Upwmhg8/lib/python3.9/site-packages/elasticsearch/client/utils.py", line 168, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/home/user/.local/share/virtualenvs/invenio-rdm-test-1Upwmhg8/lib/python3.9/site-packages/elasticsearch/client/__init__.py", line 294, in info
    return self.transport.perform_request(
  File "/home/user/.local/share/virtualenvs/invenio-rdm-test-1Upwmhg8/lib/python3.9/site-packages/elasticsearch/transport.py", line 413, in perform_request
    raise e
  File "/home/user/.local/share/virtualenvs/invenio-rdm-test-1Upwmhg8/lib/python3.9/site-packages/elasticsearch/transport.py", line 381, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/home/user/.local/share/virtualenvs/invenio-rdm-test-1Upwmhg8/lib/python3.9/site-packages/elasticsearch/connection/http_urllib3.py", line 266, in perform_request
    raise ConnectionError("N/A", str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))) caused by: ProtocolError(('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))
Failed to setup services.
```

As far as I can see from the stacktrace, the problem has something to do with elasticsearch, but for `invenio-cli services status` I get:
```
redis: up and running.
postgresql: up and running.
es: up and running.
```

## Steps to Reproduce
Setup everything following the guide. Then run `invenio-cli services setup`.

## Expected behavior
No errors.

**Comment by apirogov** [comment]
Ok I got it running for Ubuntu 20.4, Python3.8 and Node 14.

**Comment by reema-dass26** [comment]
Hello, I am facing the similar error, when i follow the instructions for v9.1 and the error occurs after :**invenio-cli services setup**
<img width="715" alt="image" src="https://github.com/user-attachments/assets/20f3821b-d845-467f-8b03-83493e293eac" />

<img width="841" alt="image" src="https://github.com/user-attachments/assets/ae47acb4-16d0-4044-be64-337ed8220e48" />


 but when i tried to use python 3.8, I get a prompt 'expected python 3.9 version for cmds:invenio-cli check-requirements --development
