### ISSUE TITLE
Visiting 127.0.0.1:5000 results in connection reset

### ISSUE THREAD

**Issue by kavonjon** [inveniosoftware/invenio-cli#296]
When trying the local install (option 2) as explained [here](https://inveniordm.docs.cern.ch/install/build-setup-run/), I get no error when running `invenio-cli run`.

When I visit 127.0.0.1 in Firefox or Chromium it only and always gives me "The connection was reset."

I am running Ubuntu 20.04, Python3.8 and Node 14.

## Steps to Reproduce
Setup everything following the guide, using the Local Install option. Then run `invenio-cli run`.

## Expected behavior
Invenio site is accessible at 127.0.0.1:5000

**Comment by spitzenwirbel** [comment]
Hello,

there is an issue with the v0.9 release:

I've used the following steps to setup InvenioRDM:

```sh
pipenv shell --python python3.9
pipenv install invenio-cli
invenio-cli init rdm -c v9.0
cd my-site/
invenio-cli containers start --lock --build --setup
```

The container which is supposed to render the website throws following exception on visit:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/flask_webpackext/manifest.py", line 27, in __getitem__
    return super(JinjaManifest, self).__getitem__(key)
  File "/usr/lib/python3.9/site-packages/pywebpack/manifests.py", line 63, in __getitem__
    return self._entries[key]
KeyError: 'base-theme-rdm.js'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.9/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1438, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
  File "/usr/lib/python3.9/site-packages/invenio_theme/views.py", line 51, in internal_error
    return render_template(current_app.config['THEME_500_TEMPLATE']), 500
  File "/usr/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/usr/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/lib/python3.9/site-packages/invenio_theme/templates/semantic-ui/invenio_theme/500.html", line 10, in top-level template code
    {% extends config.THEME_ERROR_TEMPLATE %}
  File "/usr/lib/python3.9/site-packages/invenio_theme/templates/semantic-ui/invenio_theme/page_error.html", line 11, in top-level template code
    {% extends config.THEME_BASE_TEMPLATE %}
  File "/usr/lib/python3.9/site-packages/invenio_theme/templates/semantic-ui/invenio_theme/page.html", line 72, in top-level template code
    {%- block body %}
  File "/usr/lib/python3.9/site-packages/invenio_theme/templates/semantic-ui/invenio_theme/page.html", line 103, in block 'body'
    {%- block javascript %}
  File "/usr/lib/python3.9/site-packages/invenio_theme/templates/semantic-ui/invenio_theme/page.html", line 104, in block 'javascript'
    {% include config.THEME_JAVASCRIPT_TEMPLATE %}
  File "/usr/lib/python3.9/site-packages/invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/javascript.html", line 10, in top-level template code
    {{ webpack['base-theme-rdm.js']}}
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 466, in getitem
    return obj[argument]
  File "/usr/lib/python3.9/site-packages/flask_webpackext/manifest.py", line 29, in __getitem__
    raise ManifestKeyNotFoundError('Key {} not found in manifest.json'
flask_webpackext.errors.ManifestKeyNotFoundError: Key base-theme-rdm.js not found in manifest.json
```

Version v8.0 does not have this issue.

**Comment by spitzenwirbel** [comment]
Issue seems to be resolved in v9.1
