### ISSUE TITLE
Failed to setup services

### ISSUE THREAD

**Issue by Samk13** [inveniosoftware/invenio-cli#300]
Package version (if known): [9888acd](https://github.com/inveniosoftware/invenio-cli/commit/9888acdb6b7cc408f4ac244d68fd897256273f15)

## Describe the bug
Using M1 mac:
`invenio-cli services setup` will lead to error bellow
connection to server at "localhost" (::1), port 5432 failed: FATAL:  role "my-site" does not exist
Failed to setup services.
 
## Steps to Reproduce
using M1 mac:
1. `pipenv install invenio-cli`
2. `invenio-cli invenio-cli init rdm -c master`
3. `cd my-site && invenio-cli install`
4. `invenio-cli services setup`
5. See error

## Expected behavior
setup services successfully 
## Screenshots (if applicable)
```console
(master-dev) ➜  my-site git:(master) invenio-cli services status
redis: up and running.
postgresql: up and running.
es: up and running.
(master-dev) ➜  my-site git:(master) invenio-cli services setup --force
Making sure containers are up...
redis up and running!
postgresql up and running!
es up and running!
Containers started and healthy.
Flushing Redis...
Cache cleared
Destroying database...
Destroying database postgresql+psycopg2://my-site:***@localhost/my-site
Traceback (most recent call last):
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3280, in _wrap_pool_connect
    return fn()
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 597, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: FATAL:  role "my-site" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/bin/invenio", line 8, in <module>
    sys.exit(cli())
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/flask/cli.py", line 579, in main
    return super().main(*args, **kwargs)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/flask/cli.py", line 427, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/invenio_db/cli.py", line 114, in destroy
    drop_database(_db.engine.url)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy_utils/functions/database.py", line 640, in drop_database
    with engine.connect() as connection:
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3234, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3313, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3283, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2117, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3280, in _wrap_pool_connect
    return fn()
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 597, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  role "my-site" does not exist

(Background on this error at: https://sqlalche.me/e/14/e3q8)
Failed to setup services.
Destroying indices...
Destroying indexes...
  [####################################]  100%
Purging queues...
Indexing queue has been initialized.
Indexing queue has been purged.
Updating service setup status (False)...
Service setup status updated (new value False).
Checking services are not setup...
Services setup status consistent.
Creating database...
Creating database postgresql+psycopg2://my-site:***@localhost/my-site
Traceback (most recent call last):
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3280, in _wrap_pool_connect
    return fn()
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 597, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: FATAL:  role "my-site" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/bin/invenio", line 8, in <module>
    sys.exit(cli())
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/flask/cli.py", line 579, in main
    return super().main(*args, **kwargs)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/flask/cli.py", line 427, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/invenio_db/cli.py", line 94, in init
    create_database(database_url)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy_utils/functions/database.py", line 578, in create_database
    with engine.connect() as connection:
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3234, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3313, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3283, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2117, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3280, in _wrap_pool_connect
    return fn()
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 597, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/sam-arbid/.local/share/virtualenvs/my-site-OKFw0GD5/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  role "my-site" does not exist

(Background on this error at: https://sqlalche.me/e/14/e3q8)
Failed to setup services.

```

**Comment by Samk13** [comment]
The problem was simple enough that my mac was already running an instance of Postgres that I was not aware was still running (not inside Docker) on: 5432, checked with:
`lsof -n -i:5432 | grep LISTEN`
you can't uninstall local postgress cause you will not be able to  install **psycopg2** when you do `invenio-cli install`
so I stop the service with `brew services stop postgresql` and check again if the port is free
then It compiles successfully.
