### ISSUE TITLE
logpipe not closing gracefully (--verbose)

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-cli#94]
How do we stop the local server while its running?
```
Starting celery worker...
Starting up local (development) server...
Server up and running...
```

i use ```ctrl c``` .
then i get this error:

```
Traceback (most recent call last):
  File "/home/bootcamp/developer_training/local-invenio-rdm/bin/invenio-cli", line 8, in <module>
    sys.exit(cli())
  File "/home/bootcamp/developer_training/local-invenio-rdm/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/bootcamp/developer_training/local-invenio-rdm/lib/python3.6/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/bootcamp/developer_training/local-invenio-rdm/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/bootcamp/developer_training/local-invenio-rdm/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bootcamp/developer_training/local-invenio-rdm/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bootcamp/developer_training/local-invenio-rdm/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/bootcamp/developer_training/local-invenio-rdm/lib/python3.6/site-packages/invenio_cli/cli.py", line 249, in server
    log_config=invenio_cli.log_config)
  File "/home/bootcamp/developer_training/local-invenio-rdm/lib/python3.6/site-packages/invenio_cli/helpers/scripts.py", line 357, in server
    _server_local(docker_helper, log_config)
  File "/home/bootcamp/developer_training/local-invenio-rdm/lib/python3.6/site-packages/invenio_cli/helpers/scripts.py", line 349, in _server_local
    worker.wait()
  File "/usr/lib/python3.6/subprocess.py", line 1477, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.6/subprocess.py", line 1424, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/bootcamp/developer_training/local-invenio-rdm/lib/python3.6/site-packages/invenio_cli/helpers/scripts.py", line 323, in signal_handler
    docker_helper.stop_containers()
  File "/home/bootcamp/developer_training/local-invenio-rdm/lib/python3.6/site-packages/invenio_cli/helpers/docker_helper.py", line 91, in stop_containers
    subprocess.call(command, stdout=logpipe, stderr=logpipe)
  File "/usr/lib/python3.6/subprocess.py", line 289, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.6/subprocess.py", line 1477, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.6/subprocess.py", line 1424, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/bootcamp/developer_training/local-invenio-rdm/lib/python3.6/site-packages/invenio_cli/helpers/scripts.py", line 323, in signal_handler
    docker_helper.stop_containers()
  File "/home/bootcamp/developer_training/local-invenio-rdm/lib/python3.6/site-packages/invenio_cli/helpers/docker_helper.py", line 91, in stop_containers
    subprocess.call(command, stdout=logpipe, stderr=logpipe)
  File "/usr/lib/python3.6/subprocess.py", line 289, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.6/subprocess.py", line 1477, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.6/subprocess.py", line 1424, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/bootcamp/developer_training/local-invenio-rdm/lib/python3.6/site-packages/invenio_cli/helpers/scripts.py", line 323, in signal_handler
    docker_helper.stop_containers()
  File "/home/bootcamp/developer_training/local-invenio-rdm/lib/python3.6/site-packages/invenio_cli/helpers/docker_helper.py", line 91, in stop_containers
    subprocess.call(command, stdout=logpipe, stderr=logpipe)
  File "/usr/lib/python3.6/subprocess.py", line 289, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.6/subprocess.py", line 1477, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.6/subprocess.py", line 1424, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/bootcamp/developer_training/local-invenio-rdm/lib/python3.6/site-packages/invenio_cli/helpers/scripts.py", line 323, in signal_handler
    docker_helper.stop_containers()
  File "/home/bootcamp/developer_training/local-invenio-rdm/lib/python3.6/site-packages/invenio_cli/helpers/docker_helper.py", line 91, in stop_containers
    subprocess.call(command, stdout=logpipe, stderr=logpipe)
  File "/usr/lib/python3.6/subprocess.py", line 289, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.6/subprocess.py", line 1477, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.6/subprocess.py", line 1424, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/bootcamp/developer_training/local-invenio-rdm/lib/python3.6/site-packages/invenio_cli/helpers/scripts.py", line 323, in signal_handler
    docker_helper.stop_containers()
  File "/home/bootcamp/developer_training/local-invenio-rdm/lib/python3.6/site-packages/invenio_cli/helpers/docker_helper.py", line 91, in stop_containers
    subprocess.call(command, stdout=logpipe, stderr=logpipe)
  File "/usr/lib/python3.6/subprocess.py", line 289, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.6/subprocess.py", line 1477, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.6/subprocess.py", line 1424, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/bootcamp/developer_training/local-invenio-rdm/lib/python3.6/site-packages/invenio_cli/helpers/scripts.py", line 323, in signal_handler
    docker_helper.stop_containers()
  File "/home/bootcamp/developer_training/local-invenio-rdm/lib/python3.6/site-packages/invenio_cli/helpers/docker_helper.py", line 91, in stop_containers
    subprocess.call(command, stdout=logpipe, stderr=logpipe)
  File "/usr/lib/python3.6/subprocess.py", line 289, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.6/subprocess.py", line 1477, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.6/subprocess.py", line 1424, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/bootcamp/developer_training/local-invenio-rdm/lib/python3.6/site-packages/invenio_cli/helpers/scripts.py", line 323, in signal_handler
    docker_helper.stop_containers()
  File "/home/bootcamp/developer_training/local-invenio-rdm/lib/python3.6/site-packages/invenio_cli/helpers/docker_helper.py", line 91, in stop_containers
    subprocess.call(command, stdout=logpipe, stderr=logpipe)
  File "/usr/lib/python3.6/subprocess.py", line 289, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.6/subprocess.py", line 1477, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.6/subprocess.py", line 1424, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/bootcamp/developer_training/local-invenio-rdm/lib/python3.6/site-packages/invenio_cli/helpers/scripts.py", line 326, in signal_handler
    logpipe.close()
AttributeError: 'int' object has no attribute 'close'
```

In verbose mode the variable logpipe is an integer, so logpipe.close() fails; line 326 should probably be something like this:

```
if not log_config.verbose: logpipe.close()
```

Thanks @mb-wali and @rgiaccio for the spotting and debugging.

**Comment by ppanero** [comment]
Closed in favour of #48
